#Task 1 
#Organizing a school event

students = ["John", "Doe", "Jane", "Smith"]
grades = [85, 90, 78, 88]
activities = ["Football", "Music", "Art", "Dance"]
for student, grade, and activity (students, grades, activities):
if grade < 80:
print("Name: (student), grade: (grade), activity:(activity)")

#Obtain the list of student, grade and activity of those student with a grade below 80

student = ["John" , "Doe", "Jane", "Smith"]
grades = [85, 90, 78, 88]
activities = ["Football", "Music", "Art", "Dance"]

#I am to find the range but I not quit sure so I am going to guess

for students in range(len(students)):
    if grades[:] < 80:
        print("Name:", students[:])
        print("Grade:", grades[:])
        print("Activity:",activities[:])
    # I know I missed a step here I want to try this [:] to see if I get a different outcome and not an error.
    # I thought using the slicing techniques would have work but I still recieved an error- can you give me feed 

    #Task 2 and #Task 3 is it correct that this two task can not be completed because I am unable to complete the previous task? 
    # Question: is this a true statement, that in order to complete a list of task that is using the same data, recieving an error in #task 1 can effect of what your result will be for the tast to follow ex: deep_dive_into_python? Please help!



